name: helio-synth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - sunpy
  - drms
  - astropy
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - zarr~=3.0
  - pip:
    - python-dotenv