name: helio-synth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - sunpy
  - drms
  - astropy
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pyqt
  - zarr
  - pip:
    - soundfile
    - pydub
    - pytest
    - python-dotenv